### ISSUE TITLE
i06t09: Coral methods

### ISSUE THREAD

**Issue by brunokam** [OceanVision/ocean#101]
- Extended description: Create stubs of the methods which are responsible for collecting data and sending it to Android app.
- Time estimation: 3h

**Comment by kudkudak** [comment]
Consider using Scala and Akka. Here are my arguments:
- It is basically endless fun 
- We are writing more and more backend in Scala : Akka gives us for free just awesome communication
- Python is slow, and Coral will be extensively used (assuming Coral is also putting together the feeds, not only passing this responsibility to other module. I think Coral should do it, as the name is very appropriate)
