### ISSUE TITLE
i06t06: Introduction of the embedded Neo4j API to Lionfish

### ISSUE THREAD

**Issue by brunokam** [OceanVision/ocean#102]
- Extended description: Rewrite Lionfish server to Scala and connect with the embedded Neo4j API.
- Time estimation: 4h

**Comment by ktalik** [comment]
Methods that I'll need in Lionfish client:
- delete property from node
- overwrite node with dictionary of new properties (of course `uuid` remains the same)
- `set` method for relations
- delete property from relation
- overwrite relation properties
- limit results (Cypher LIMIT keyword)

**Comment by ktalik** [comment]
- `CREATE UNIQUE` for relation and for node

**Comment by brunokam** [comment]
I will continue my work in a different task.

**Comment by kudkudak** [comment]
This is a great idea. Good luck buddy!
