### ISSUE TITLE
Minor issues Spidercrab

### ISSUE THREAD

**Issue by kudkudak** [OceanVision/ocean#151]
Adding here just for reference:
- Spidercrab correctness test is not asserting at the end
- Spidercrab should check if the database is correct (I had problem because tests were failing and it was due to _incorrect init scripts_) - corrected scripts on mantis_shrimp branch
- I have added checking stats file, but I guess you might want to handle it differently (changes on mantis_shrimp branch - maybe you can do it after merging?)
- I have removed checking for neo4j in the integrity test because new lionfish is running itself neo4j , and might not run REST UI on port 7474(changes on mantis_shrimp branch - maybe you can do it after merging?)

**Comment by ktalik** [comment]
> Spidercrab correctness test is not asserting at the end

Don't really know what kind of assertion should be there, since integrity test and "1000" test will assert averything. I can add test (correctness) coverage assertion.

> Spidercrab should check if the database is correct

Well... If you really need this I can add this functionality... But this should raise an exception.

> (I had problem because tests were failing and it was due to incorrect init scripts) - corrected scripts on mantis_shrimp branch

Could you please provide a commit hash here? (and eventually script file name?)

> I have added checking stats file, but I guess you might want to handle it differently (changes on mantis_shrimp branch - maybe you can do it after merging?)

(as above)

> I have removed checking for neo4j in the integrity test because new lionfish is running itself neo4j , and might not run REST UI on port 7474(changes on mantis_shrimp branch - maybe you can do it after merging?)

OK -- you have removed it. Maybe I can do... what?

**Comment by kudkudak** [comment]
There are some major issues with lionfish, we will get back to those minor issues later. Regarding scripts please download whole directory scripts from mantis_shrimp branych.  Regarding test: well it is correctness_TEST, and it is not saying if it has passed or not ;)
