### ISSUE TITLE
Bugs lionfish

### ISSUE THREAD

**Issue by kudkudak** [OceanVision/ocean#152]
- Too big request: [ERROR] [05/18/2014 11:39:52.403] [proxySystem-akka.remote.default-remote-dispatcher-4] [akka.tcp://proxySystem@localhost:7777/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FstreamSystem%40localhost%3A7776-0/endpointWriter] Transient association error (association remains live)
  akka.remote.OversizedPayloadException: Discarding oversized payload sent to Actor[akka.tcp://streamSystem@localhost:7776/temp/$p]: max allowed size 128000 bytes, actual size of encoded class scala.collection.immutable.$colon$colon was 152653 bytes.
- Cannot run 2 clients? Both try to bind on 7776 (akka)? Scenario: run application using client and tests
- Stream is returning void
- Hanging lionfish: you should use Ask, Future functionality (see mantis_shrimp main.scala for example) which will return error if not received message.
- Setting in Database proxy host = 127.0.0.1 is not same as setting host = localhost!!
- Add comments !! ;p (at least in **Database.scala** file)
- Refactor proxyAddress to serverAddress - it is more intuitive
- CreateNode is returning whole node, unnecessary connection usage

**Comment by brunokam** [comment]
The bugs seems to be solved. I'd like to mention the last issue. CreateNode does not return a whole node - just its uuid.
