### ISSUE TITLE
Cypher doesn't accept "<" in relation name!

### ISSUE THREAD

**Issue by kudkudak** [OceanVision/ocean#23]
neo4django defines relations with "<" in name, like "<<TYPE>>", but I think that Cypher doesn't accept this character in queries.

TODO: Investigate if it is possible to pass "<" in cypher query (like MATCH n->[r:<<TYPE>>]->c), if not modify neo4django

**Comment by ktalik** [comment]
Note: In Neo4j documentation they are using _oblique_ quotation marks in queries with "weird stuff". Maybe thats a solution:

> - An identifier: n, x, rel, myFancyIdentifier, `A name with weird stuff in it[]!`. 
> - A property: n.prop, x.prop, rel.thisProperty, myFancyIdentifier.`(weird property name)`.

http://docs.neo4j.org/chunked/milestone/cypher-expressions.html#_expressions_in_general

**Comment by ktalik** [comment]
Solved.
