### ISSUE TITLE
What's going on with the adding new channel functionality

### ISSUE THREAD

**Issue by ktalik** [OceanVision/ocean#28]
Some of RSS channels are having problems:
1. Adding fails, and then, after a few attemps it adds channel properly.
2. Some of the channels wont be added after deletion from user interface (relationship deletion).
   
   f.e.: http://www.tvn24.pl/wiadomosci-krakow,50.xml

**Comment by kudkudak** [comment]
I think that problem is with "," and other special characters..

**Comment by snakoneczny** [comment]
Problem with xml parsing, now it will work with all kind of missing nodes.
