### ISSUE TITLE
get_rss_content critically inefficient

### ISSUE THREAD

**Issue by kudkudak** [OceanVision/ocean#31]
This code scans through all the news EVER produced.

```
        for rss_channel in user.subscribes_to.all():
            for news in rss_channel.produces.all():
                news_dict = news.__dict__["_prop_values"]
                news_dict['pk'] = news.pk
                news_dict['color'] = colors[random.randint(0, 4)]
                rss_items_array.append(news_dict)
```

Not sure how to fix it, we have to design something for that..

**Comment by ktalik** [comment]
The answer is Cypher in OceanDatabaseManager.

**Comment by kudkudak** [comment]
The answer is coding everything as GraphViews.

Just moving it to ODM doesn't solve anything

I am just pushing commit with OceanMaster skeleton, that is managing Graph Views. Then we will ahve to code GraphView that will keep most recent news from each newswebsite.

This way we get from O(N) to O(K), where N is number of all news is system, K is window size we want to keep
