### ISSUE TITLE
TypeError: $(...).qtip is not a function

### ISSUE THREAD

**Issue by ktalik** [OceanVision/ocean#41]
There is a workaround in current version of code in [visualisation.js](/bziiuj/ocean/blob/2e828d4bae0dc80b4772ee795d2d7f2f9ecb7521/webservice/static/base/visualization.js), currently from line [216](/bziiuj/ocean/blob/2e828d4bae0dc80b4772ee795d2d7f2f9ecb7521/webservice/static/base/visualization.js#L215) to [238](/bziiuj/ocean/blob/2e828d4bae0dc80b4772ee795d2d7f2f9ecb7521/webservice/static/base/visualization.js#L238).

After commenting workaround (those two lines) crash appears.

Reproduction:
1. Comment those two lines
2. Run `python manage.py runserver`
3. Go to ocean webpage (or refresh to reload JavaScripts)
4. Go to `/rss` page
5. Click `profile` or `account` link. It will launch f.e. `javascript:main.load('edit_profile')`.
6. Crash should occur. Read web console. You should see something like:

```
[<<localtime>>] TypeError: $(...).qtip is not a function @ http://127.0.0.1:8000/static/base/jquery-1.10.2.min.js:225
```

Is it a problem of catenation `?ajax=ok` to every url in `javascript:main.load(url)` ?

**Comment by brunokam** [comment]
This bug will be resolved by rewriting the frontend.
