### ISSUE TITLE
Fix signing in functionality

### ISSUE THREAD

**Issue by brunokam** [OceanVision/ocean#43]
- Estimation: 2 h

**Comment by ktalik** [comment]
> i04t03: Fix signing in functionality

**signing in** or **signing up**?

As far as I remember task is related to registration not loggin in. Signing in means logging in, and it works. Registration is also called "signing up". Changed taks title.

**Comment by kudkudak** [comment]
No - signing in doesn't work (at least some times)

**Comment by ktalik** [comment]
Rolled back issue changes.
