### ISSUE TITLE
Task i01t05: Tools integration (neo4j, django)

### ISSUE THREAD

**Issue by ktalik** [OceanVision/ocean#5]
- Description: Integrate tools (neo4j, django)
- Extended description: Include exemplary data and code store format from task i01t03 (#3)
- Task depends on the other tasks: i01t01 (#1)
- Risk factors: Time estimation could be too short. The integration process may produce new problems.
- Estimation: 4h

**Comment by kudkudak** [comment]
Not done. Gremlin doesn't compile with neo4j 2.0. Therefore it is necessary to downgrade to 1.9.

Still models from ocean_exemplary_data.py are not visible in django webservice.
