### ISSUE TITLE
News display formatting issues with some feeds

### ISSUE THREAD

**Issue by ktalik** [OceanVision/ocean#68]
There are issues with formatting content in news display:

example (rss.feedsportal.com)
![przechwycenie obrazu ekranu - 24 01 2014 - 00 42 41](https://f.cloud.github.com/assets/858917/1990632/2a1d600c-8488-11e3-9790-d8e372f6e344.png)

**Comment by brunokam** [comment]
This bug will be resolved by rewriting the frontend.
