### ISSUE TITLE
i05t09: News fetching and extraction technology research

### ISSUE THREAD

**Issue by kudkudak** [OceanVision/ocean#71]
See if there is existing software more suitable for writing perfect webcrawler in few weeks.

Few things I have stumbled upon
1. BeautifulSoup
2. import.io
3. http://scrapy.org/

**Comment by kudkudak** [comment]
http://codingwiththomas.blogspot.com/2013/01/extracting-articles-from-crawled-html.html

Machine learning approach to extracting news - I like it. Import.io is simillar i think

**Comment by ktalik** [comment]
Research conclusions can be found [here](../wiki/Spidercrab).
